console.log('1. Loading config/database...');
require('./config/database');
console.log('2. Loading services/emailService...');
require('./services/emailService');
console.log('3. Loading controllers/authController...');
require('./controllers/authController');
console.log('4. Loading middleware/auth...');
require('./middleware/auth');
console.log('5. Loading routes/authRoutes...');
require('./routes/authRoutes');
console.log('All dependencies loaded successfully');
process.exit(0);
