import React, { createContext, useContext, useState, useEffect, ReactNode } from 'react';

type Language = 'PT' | 'EN';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  langData: any;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

const translations = {
  PT: {
    // Welcome & Auth
    welcome_title: "Controle suas calorias de forma fácil",
    welcome_subtitle: "A maneira mais inteligente de atingir seus objetivos fitness com IA.",
    start_quiz: "Iniciar Quiz",
    already_have_account: "Já tem uma conta?",
    login_here: "Entre aqui",
    create_account: "Criar conta",
    welcome_back: "Bem-vindo de volta",
    login_to_account: "Faça login na sua conta",
    register_title: "Crie sua conta",
    register_subtitle: "Salve seu progresso e comece sua jornada",
    auth_login_button: "Entrar",
    auth_forgot_password: "Esqueceu a senha?",
    auth_no_account: "Não tem uma conta?",
    auth_password_placeholder: "Senha",
    auth_have_account: "Já tem uma conta?",
    auth_login_title: "Entrar",
    auth_error_server: "Erro ao conectar com servidor.",
    start_transformation: "Começar Minha Transformação",
    continue: "Continuar",
    back: "Voltar",
    skip: "Pular",

    // Quiz - Steps 1-10
    quiz_step_gender_title: "Qual o seu gênero?",
    quiz_gender_male: "Masculino",
    quiz_gender_female: "Feminino",
    quiz_gender_other: "Outro",
    quiz_step_goal_title: "Qual o seu principal objetivo?",
    quiz_goal_lose: "Perder peso",
    quiz_goal_maintain: "Manter peso",
    quiz_goal_gain: "Ganhar massa",
    quiz_step_age_title: "Qual a sua idade?",
    quiz_step_height_title: "Qual a sua altura?",
    quiz_step_weight_title: "Qual o seu peso atual?",
    quiz_step_target_weight_title: "Qual o seu peso ideal?",
    quiz_day: "Dia",
    quiz_month: "Mês",
    quiz_year: "Ano",
    quiz_step_feeling_title: "Como você se sente hoje em relação ao seu peso?",
    quiz_feeling_frustrated: "Frustrado(a) e arrependido(a) de não ter agido antes",
    quiz_feeling_avoidance: "Evito me olhar no espelho ou tirar fotos",
    quiz_feeling_resigned: "Conformado(a), já me acostumei com isso",
    quiz_feeling_determined: "Determinado(a) a mudar finalmente",
    quiz_feeling_unhappy: "Infeliz",
    quiz_feeling_could_be_better: "Poderia ser melhor",
    quiz_feeling_neutral: "Neutro",
    quiz_feeling_confident: "Confiante",

    // Quiz - Velocity & Charts
    quiz_step_velocity_title: "Qual a velocidade que você quer atingir seu objetivo?",
    quiz_velocity_per_week: "por semana",
    quiz_velocity_subtitle: "por semana",
    quiz_velocity_recommended: "Ritmo recomendado",
    quiz_chart_loss_title: "Perca duas vezes mais peso com o ProFit",
    quiz_chart_gain_title: "Ganhe duas vezes mais massa com o ProFit",
    quiz_chart_subtitle: "Estudos científicos mostram que usar o ProFit aumenta sua taxa de sucesso",
    quiz_chart_standard: "Abordagem padrão",
    quiz_chart_profit: "Com suporte ProFit",
    quiz_chart_footer: "O ProFit facilita e te mantém comprometido",

    // Quiz - Obstacles & Goals
    quiz_step_obstacles_title: "O que está te impedindo de atingir seus objetivos?",
    quiz_obstacles_subtitle: "Selecione todas as opções que se aplicam",
    quiz_obstacle_consistency: "Falta de consistência",
    quiz_obstacle_habits: "Hábitos alimentares não saudáveis",
    quiz_obstacle_support: "Falta de suporte",
    quiz_obstacle_schedule: "Agenda ocupada",
    quiz_obstacle_inspiration: "Falta de inspiração para refeições",
    quiz_step_conquer_title: "O que você gostaria de conquistar?",
    quiz_goals_subtitle: "Selecione todas as opções que se aplicam",
    quiz_goal_health: "Comer e viver de forma mais saudável",
    quiz_goal_energy: "Aumentar minha energia e humor",
    quiz_goal_motivation: "Me manter motivado e consistente",
    quiz_goal_body: "Me sentir melhor com meu corpo",

    // Quiz - Evolution Chart
    quiz_step_evolution_title: "Sua musculatura responde melhor do que você imagina",
    quiz_evolution_3days: "3 Dias",
    quiz_evolution_7days: "7 Dias",
    quiz_evolution_30days: "30 Dias",
    quiz_evolution_footer: "Dados do ProFit mostram que sua síntese proteica aumenta desde o primeiro treino. Após 7 dias de constância, a construção muscular entra em ritmo acelerado e constante!",

    // Quiz - Calories Education
    quiz_step_calories_intro: "Você sabe o que são calorias e sua importância para {goal}?",
    quiz_goal_text_lose: "perder peso",
    quiz_goal_text_gain: "ganhar peso",
    quiz_goal_text_maintain: "manter seu peso",
    quiz_yes: "Sim",
    quiz_no: "Não",
    quiz_step_explain_title: "Vamos te explicar!",
    quiz_explain_p1: "Calorias são a energia que os alimentos fornecem ao seu corpo.",
    quiz_explain_p2: "Cada comida tem uma quantidade diferente:",
    quiz_explain_banana: "1 banana",
    quiz_explain_bread: "1 fatia de pão",
    quiz_explain_rice: "1 colher de arroz",
    quiz_step_how_helps_title: "Como isso te ajuda a {goal}?",
    quiz_helps_lose_p1: "Para emagrecer, você precisa estar em déficit calórico, que é consumir menos calorias do que seu corpo gasta.",
    quiz_helps_lose_p2: "Se você gasta 2000 calorias por dia, precisa comer cerca de 1500-1700 para emagrecer de forma saudável.",
    quiz_helps_gain_p1: "Para ganhar massa muscular, você precisa estar em superávit calórico, que é consumir mais calorias do que seu corpo gasta.",
    quiz_helps_gain_p2: "Se você gasta 2000 calorias por dia, precisa comer cerca de 2300-2500 calorias por dia para ganhar peso.",
    quiz_helps_maintain_p1: "Para manter seu peso, você precisa consumir a mesma quantidade de calorias que seu corpo gasta diariamente.",
    quiz_helps_maintain_p2: "Se você gasta 2000 calorias por dia, deve consumir em torno de 2000 calorias para manter seu peso.",
    quiz_helps_footer: "Com o ProFit, você vai conseguir implementar isso de forma simples e segura!",
    quiz_step_base_title: "Ótimo, você já tem uma base!",
    quiz_base_p1: "Vamos te ajudar a usar esse conhecimento ao seu favor.",
    quiz_base_p2: "O ProFit agora vai te ajudar exatamente a alcançar seu objetivo de {goal}.",

    // Quiz - Activity & Social Proof
    quiz_step_activity_title: "Qual é o seu nível de atividade física?",
    quiz_activity_subtitle: "Isso nos ajuda a calcular sua quebra calórica diária",
    quiz_activity_sedentary: "Sedentário",
    quiz_activity_sedentary_desc: "Trabalho de escritório, pouco exercício",
    quiz_activity_light: "Levemente Ativo",
    quiz_activity_light_desc: "Exercício leve 1-3 dias/semana",
    quiz_activity_moderate: "Moderadamente Ativo",
    quiz_activity_moderate_desc: "Exercício moderado 3-5 dias/semana",
    quiz_activity_very: "Muito Ativo",
    quiz_activity_very_desc: "Exercício intenso 6-7 dias/semana",
    quiz_activity_extra: "Extremamente Ativo",
    quiz_activity_extra_desc: "Treino pesado 2x ao dia, atleta",
    quiz_step_social_title: "Faça como o Lucas",
    quiz_social_subtitle: "E perca o peso desejado com ProFit",
    quiz_social_before: "ANTES",
    quiz_social_after: "DEPOIS",
    quiz_social_lost: "PESO PERDIDO",
    quiz_social_mass: "MASSA GANHA",
    quiz_social_duration: "DURAÇÃO",
    quiz_social_quote: "\"Perder peso parecia impossível, mas o ProFit mudou tudo.\"",
    quiz_social_user: "Lucas, usuário ProFit",
    
    // Emanuel - Ganhar Massa
    quiz_emanuel_name: "Emanuel",
    quiz_emanuel_stats: "+12kg de Massa Magra",
    quiz_emanuel_duration: "6 Meses",
    quiz_emanuel_quote: "\"O ProFit me deu o caminho exato. Ganhei músculos que nunca achei possível apenas mudando minha dieta e treinos!\"",
    quiz_emanuel_user: "Emanuel, usuário ProFit",

    // Fátima - Emagrecer
    quiz_fatima_name: "Dona Fátima",
    quiz_fatima_stats: "-22kg Eliminados",
    quiz_fatima_duration: "4 Meses",
    quiz_fatima_quote: "\"Aos 55 anos, o ProFit simplificou minha alimentação e hoje me sinto 20 anos mais jovem!\"",
    quiz_fatima_user: "Dona Fátima, usuário ProFit",
    quiz_step_stories_title: "Histórias de Sucesso",
    quiz_stories_subtitle: "Milhares de usuários alcançando seus objetivos",
    quiz_stories_count: "+1.000 usuários com o ProFit",
    quiz_stories_card_title: "O único que consegui manter",
    quiz_stories_card_text: "Sempre desistia em 2 semanas. A gamificação e as metas reais do ProFit me mantiveram motivado. Já são 6 meses de evolução constante!",
    quiz_stories_footer_title: "Você está no caminho certo!",
    quiz_stories_footer_text: "Junte-se a milhares de usuários satisfeitos e comece sua jornada hoje",

    // Quiz - Evolution (New Step 25)
    quiz_step_evolution_promo_title: "COMECE SUA EVOLUÇÃO COM O PROFIT AGORA",
    quiz_evolution_no_payment: "Sem pagamentos feitos agora",
    quiz_evolution_scan: "ESCANEAR REFEIÇÃO",
    quiz_evolution_gallery: "GALERIA",

    // Quiz - Why ProFit & Notifications
    quiz_step_why_title: "Por que o ProFit é o app ideal para você?",
    quiz_why_subtitle: "Unimos ciência e inteligência artificial para facilitar sua transformação",
    quiz_why_time_title: "Economize seu tempo",
    quiz_why_time_text: "Nossa IA calcula e registra sua comida em segundos por foto, voz ou texto. Chega de buscas manuais cansativas.",
    quiz_why_freedom_title: "Liberdade Alimentar",
    quiz_why_freedom_text: "Aprenda a comer o que gosta batendo suas metas. Controle total, zero restrições inúteis.",
    quiz_why_conf_title: "Confiança no Espelho",
    quiz_why_conf_text: "90% dos usuários relatam sentir-se muito mais atraentes e seguros com o próprio corpo em 30 dias.",
    quiz_why_energy_title: "Energia Diária",
    quiz_why_energy_text: "Diga adeus à fadiga e ao inchaço. Sinta a diferença na sua disposição logo nos primeiros dias.",
    quiz_step_notif_title: "Mantenha o Foco",
    quiz_notif_subtitle: "Ative as notificações para receber atualizações personalizadas.",
    quiz_notif_stat: "Usuários com notificações têm 3x mais chances de alcançar metas.",
    quiz_notif_allow: "Permitir Notificações",
    quiz_notif_later: "Talvez Mais Tarde",
    quiz_notif_preview_report: "Seu relatório semanal de progresso está pronto!",
    quiz_notif_preview_meal: "Não se esqueça de registrar seu almoço.",
    quiz_notif_preview_streak: "Você atingiu uma sequência de 7 dias!",
    quiz_notif_preview_water: "Hora de beber água! Faltam 500ml.",

    // Quiz - Referral & Account
    quiz_step_referral_source_title: "Onde você ouviu falar do ProFit?",
    quiz_referral_source_subtitle: "Isso nos ajuda a melhorar nossa comunicação",
    quiz_referral_other: "Outro",
    quiz_step_name_title: "Prazer em conhecê-lo!",
    quiz_name_subtitle: "Qual o seu nome?",
    quiz_name_label: "Nome",
    quiz_name_placeholder: "Digite seu nome",
    quiz_step_email_title: "Agora vamos criar sua conta",
    quiz_email_subtitle: "Digite seu melhor e-mail",
    quiz_email_label: "E-mail",
    quiz_email_placeholder: "Digite seu e-mail",
    quiz_step_phone_title: "Para finalizarmos",
    quiz_phone_subtitle: "Compartilhe seu telefone conosco",
    quiz_phone_label: "Telefone",
    quiz_phone_placeholder: "Digite seu telefone",
    quiz_step_referral_code_title: "Você tem um código de indicação?",
    quiz_referral_code_subtitle: "Você pode pular esta etapa",
    quiz_referral_code_label: "Código de Indicação",
    quiz_referral_code_placeholder: "Código de Indicação",

    // Quiz - Analysis & Result
    quiz_analysis_title_1: "Ajustando sua experiência",
    quiz_analysis_title_2: "Personalizando sua estratégia ProFit",
    quiz_analysis_title_3: "Criando sua conta no ProFit",
    quiz_analysis_data: "Analisando seus dados",
    quiz_analysis_health: "Calculando sua pontuação de saúde",
    quiz_analysis_macros: "Calculando os macros",
    quiz_analysis_review: "Revisando tudo",
    quiz_analysis_proof_title: "Mais de 5.000",
    quiz_analysis_proof_subtitle: "Avaliações 5 estrelas",
    quiz_step_final_title: "Plano ProFit Gerado!",
    quiz_final_macros_desc: "Precisão para sua meta",
    quiz_final_button: "Acessar Meu Plano AGORA",
    
    // Quiz Results - Step 34
    quiz_results_congrats: "Parabéns!",
    quiz_results_ready: "Seu plano personalizado está pronto!",
    quiz_results_gain: "Você deve ganhar peso:",
    quiz_results_lose: "Você deve perder peso:",
    quiz_results_maintain_goal: "Você deve manter seu peso:",
    quiz_results_kg_until: "kg até",
    quiz_results_daily_rec: "Recomendação diária",
    quiz_results_edit_anytime: "Você pode editar isso a qualquer momento",
    quiz_results_calories: "Calorias",
    quiz_results_carbs: "Carbo",
    quiz_results_protein: "Proteína",
    quiz_results_fats: "Gorduras",
    quiz_results_health_score: "Pontuação de Saúde",
    quiz_results_how_to_reach: "Como alcançar seus objetivos",
    quiz_results_benefit_1: "Veja resultados reais em dias, não meses",
    quiz_results_benefit_2: "Cada refeição te aproxima da meta ou te afasta - escolha certo",
    quiz_results_benefit_3: "Acelere sua queima de gordura comendo as calorias certas",
    quiz_results_benefit_4: "O equilíbrio perfeito entre perder peso e manter energia",
    quiz_results_research_title: "Pesquisas que utilizamos para considerar nossos cálculos:",
    quiz_results_button: "Pegue os seus 3 dias grátis",
    
    // Quiz Free Trial - Step 35
    quiz_free_trial_title: "Queremos que você teste o FitCal GRÁTIS",
    quiz_free_trial_subtitle: "Sem pagamentos feito agora",
    quiz_scan_meal: "Escanear Refeição",
    quiz_gallery: "Galeria",
    quiz_privacy: "Privacidade",
    quiz_restore: "Restaurar Compras",
    quiz_terms: "Termos",
    
    // Quiz Subscription - Step 36
    quiz_timeline_title: "grátis... 😔",
    quiz_timeline_today_title: "Hoje",
    quiz_timeline_today_sub: "Receba acesso total ao FitCal para registrar suas refeições com IA",
    quiz_timeline_reminder_title: "Em 0 Dias - Lembrete",
    quiz_timeline_reminder_sub: "Vamos enviar um lembrete que o seu teste grátis está acabando",
    quiz_timeline_charge_title: "Em 0 Dias",
    quiz_timeline_charge_sub: "Sua inscrição vai começar {date} se você não tiver cancelado",
    quiz_subscription_monthly: "MENSAL",
    quiz_subscription_price_mzn: "299 MT / mês",
    quiz_subscription_change_body: "Não perca a oportunidade de mudar seu corpo!",
    quiz_subscription_cancel_anytime: "Cancele quando quiser!",
    quiz_subscription_commitment: "Sem compromisso, cancele quando quiser.",

    // Quiz - Dynamic Results (Steps 9-11)
    quiz_feeling_result_determinado_title: "Você disse que está determinado(a). Essa é a energia que você precisa. {todayStr}",
    quiz_feeling_result_determinado_sub: "Use essa determinação agora para fazer acontecer de verdade.",
    quiz_feeling_result_conformado_title: "Você disse que já se acostumou. Mas lá no fundo você quer mudar. {todayStr}",
    quiz_feeling_result_conformado_sub: "Aproveite para sair dessa zona de conforto.",
    quiz_feeling_result_frustrado_title: "Você disse que se sente frustrado(a). {todayStr}",
    quiz_feeling_result_frustrado_sub: "Não deixe essa frustração te acompanhar o ano todo. Mude a rota agora.",
    quiz_feeling_result_evito_title: "Você disse que acaba evitando situações... {todayStr}",
    quiz_feeling_result_evito_sub: "Não precisa ser assim. Quebre esse ciclo agora.",
    quiz_goal_realistic_title: "{goalText} {goalVal} é uma meta REALISTA. E acredite: não é nada difícil!",
    quiz_goal_realistic_sub: "O segredo para não desistir é começar com uma meta possível como a sua.",
    quiz_motivation_lose_title: "Alcançar sua melhor forma é um investimento na sua saúde.",
    quiz_motivation_lose_sub: "Independente do seu ponto de partida, focar na qualidade da sua alimentação garante mais longevidade e energia.",
    quiz_motivation_gain_title: "Sua melhor versão está esperando para ser construída.",
    quiz_motivation_gain_sub: "Ganhar massa muscular de forma limpa requer precisão nos macros. Com o ProFit, você garante que cada caloria conte.",
    quiz_motivation_maintain_title: "Sua saúde e vitalidade são o seu maior patrimônio.",
    quiz_motivation_maintain_sub: "Manter o peso de forma sustentável é o que garante longevidade e energia. O ProFit simplifica a sua rotina.",

    // Dashboard
    dash_hello_morning: "Bom dia",
    dash_hello_afternoon: "Boa tarde",
    dash_hello_night: "Boa noite",
    dash_today: "Hoje",
    dash_consumed_today: "Consumido hoje",
    dash_goal: "Meta",
    dash_of_goal: "da meta",
    dash_protein: "Proteína",
    dash_carbs: "Carbos",
    dash_fat: "Gordura",
    dash_no_workout: "Você ainda não tem um plano de treino.",
    dash_create_workout: "Criar meu plano",
    dash_workout_today: "Treino de Hoje",
    dash_workout_exercises: "Exercícios",
    dash_workout_focus: "Foco",
    dash_workout_rest: "Aproveite para descansar e recuperar suas energias! ⚡",
    dash_workout_view_all: "Ver plano completo",
    dash_delete_meal: "Excluir?",
    dash_yes: "Sim",
    dash_no: "Não",
    dash_error_title: "Ops! Algo deu errado",
    dash_retry: "Tentar novamente",
    dash_analysis_message: "Ver Mensagem",
    dash_body_analysis: "Ver Análise Corporal",
    dash_ai_vision: "Análise Baseada em Visão IA",
    dash_load_error: "Não foi possível carregar seus dados. Verifique sua conexão.",
    dash_days_short: ['Dom', 'Seg', 'Ter', 'Qua', 'Qui', 'Sex', 'Sáb'],
    dash_valid_until: "Válido até",
    dash_plan_expires_in: "Plano Expira em",
    dash_day: "dia",
    dash_days: "dias",
    dash_renew_now: "Renove agora para manter o Pro",
    dash_meals_title: "Refeições registradas",
    dash_view_all: "Ver tudo",
    dash_no_meals: "Nenhuma refeição registrada recentemente.",
    dash_calories: "Calorias",

    // Scan
    scan_analyzing: "Analisando...",
    scan_identified_dish: "Prato Identificado",
    scan_error_save: "Ocorreu um erro ao salvar a refeição. Tente novamente.",
    scan_share_title: "Meu Prato no ProFit",
    scan_share_text: "Confira minha refeição no ProFit! 🥗\nPrato: {name}\nCalorias: {calories} kcal\n{obs}",
    scan_link_copied: "Link copiado para a área de transferência!",
    scan_ai_suggestion: "Sugestão IA",
    scan_daily_goal: "Meta Diária",
    scan_kcal_remaining: "kcal restantes",
    scan_nutrition_obs: "Observação Nutricional",
    scan_no_obs: "Não há observações para este prato.",
    scan_ingredients_title: "Ingredientes Identificados",
    scan_no_ingredients: "Nenhum ingrediente identificado.",
    scan_redo: "Refazer",
    save: "SALVAR",
    ok: "OK",
    success: "Sucesso!",
    error: "Erro",
    close: "Fechar",

    // Workouts
    wk_ia_title: "Treinos IA",
    wk_confirm: "Confirmar",
    wk_back: "Voltar",
    wk_continue: "Continuar",
    wk_generate: "Gerar Plano",
    wk_fill_all: "Preencha todos os campos para continuar *",
    wk_loading_1: "Estamos criando seu plano personalizado...",
    wk_loading_2: "Analisando seu perfil e histórico...",
    wk_loading_3: "Montando sua estratégia ideal de treino...",
    wk_loading_4: "Finalizando os detalhes técnicos...",
    wk_sync_ia: "Sincronizando IA Master Coach",
    wk_active_plan_title: "Plano Ativo",
    wk_active_plan_msg: "Você já possui um plano ativo. Termine o atual antes de gerar outro.",
    wk_understand: "Entendi",
    wk_ia_coach_title: "IA Master Coach 🤖",
    wk_ia_demand_msg: "Nossa IA está com alta demanda técnica agora. Podemos carregar um Plano de Transição ProFit para você não ficar parado hoje?",
    wk_use_fallback: "Usar Plano de Transição",
    wk_step_1_title: "Construindo Seu Plano Sob Medida",
    wk_goal: "Objetivo",
    wk_level: "Nível",
    wk_days_week: "Dias/Semana",
    wk_location: "Local de Treino",
    wk_age: "Idade",
    wk_weight: "Peso (kg)",
    wk_height: "Altura (cm)",
    wk_duration: "Duração",
    wk_intensity: "Intensidade",
    wk_trained_before: "Já treinou antes?",
    wk_training_time: "Tempo de treino",
    wk_body_focus: "Foco Corporal",
    wk_injuries: "Lesões ou Dores?",
    wk_health_conditions: "Doenças ou Condições?",
    wk_notes: "Algo mais?",
    wk_notes_placeholder: "Descreva algo importante sobre você",
    wk_ia_analysis_title: "Análise Corporal por IA",
    wk_ia_analysis_desc: "Envie uma foto do seu corpo inteiro (frente) para uma análise MASTER de pontos fortes e fracos.",
    wk_select_photo: "Selecionar Foto",
    wk_optional_formats: "Opcional • Formatos JPG, PNG",
    wk_ia_privacy_note: "A IA analisará seu percentual de gordura estimado e estrutura muscular para hiper-personalizar seu treino. Imagem segura e privada.",
    wk_attention: "Atenção ⚠️",
    wk_warning_msg: "Você está prestes a gerar seu plano de treino do mês.",
    wk_validity_msg: "Este plano será válido durante os próximos 30 dias e não poderá ser alterado até o próximo ciclo.",
    wk_update_now: "Atualizar Agora",
    wk_confirm_generate: "Confirmar e Gerar",
    wk_creating_custom: "Estamos criando seu",
    wk_custom_plan: "Plano Personalizado",
    wk_preparing: "Preparando seu treino pro...",
    wk_workout_of: "Treino de",
    wk_coach_tip: "Dica do Master Coach",
    wk_total_progress: "Progresso Total",
    wk_exercises: "exercícios",
    wk_rest: "descanso",
    wk_suggested_load: "Carga sugerida",
    wk_volume: "Volume",
    wk_sets_series: "séries",
    wk_completed_sets: "Séries concluídas",
    wk_mark_done: "MARCAR EXERCÍCIO COMO FEITO",
    wk_workout_done: "Treino Pago! 🔥",
    wk_excellent_work: "Excelente trabalho hoje. O corpo responde ao esforço consistente!",
    wk_est_kcal: "Kcal Est.",
    wk_time: "Tempo",
    wk_see_tomorrow: "Até amanhã! 💪",

    // Bottom Nav
    nav_home: "Início",
    nav_scanner: "Scanner",
    nav_workout: "Treino",
    nav_profile: "Perfil",

    // Profile
    profile_title: "Perfil",
    profile_name_placeholder: "Seu nome",
    profile_goal_default: "OBJETIVO GERAL",
    profile_weight: "Peso",
    profile_height: "Altura",
    profile_age: "Idade",
    profile_years: "anos",
    profile_menu_notifications: "Notificações",
    profile_menu_notifications_desc: "Alertas de app e lembretes",
    profile_menu_achievements: "Conquistas",
    profile_menu_achievements_desc: "Seus emblemas e troféus",
    profile_menu_ai_chat: "Dúvidas com IA",
    profile_menu_ai_chat_desc: "Assistente fitness especializado",
    profile_menu_preferences: "Preferências",
    profile_menu_preferences_desc: "Tema e linguagem",
    profile_menu_account: "Conta",
    profile_menu_account_desc: "Dados pessoais, Meta de Kcal",
    profile_logout: "Sair",
    profile_notif_enabled: "Ativado",
    profile_notif_disabled: "Desativado",
    profile_modal_notif_title: "Desativar notificações?",
    profile_modal_notif_msg: "Você deixará de receber lembretes importantes sobre suas metas e refeições.",
    profile_modal_confirm: "Desativar",
    profile_modal_cancel: "Cancelar",

    // Quiz Extra Components
    quiz_lucas_lost_val: "-20Kg",
    quiz_lucas_duration_val: "3 Meses",
    quiz_success_users: "+1.000 usuários com o ProFit",
    quiz_success_comment_title: "O único que consegui manter",
    quiz_success_comment_text: "Sempre desistia em 2 semanas. A gamificação e as metas reais do ProFit me mantiveram motivado. Já são 6 meses de evolução constante!",
    quiz_success_footer_title: "Você está no caminho certo!",
    quiz_success_footer_text: "Junte-se a milhares de usuários satisfeitos e comece sua jornada hoje",
    quiz_notif_now: "AGORA",
    quiz_notif_report: "Seu relatório semanal de progresso está pronto!",
    quiz_notif_lunch: "Não se esqueça de registrar seu almoço.",
    quiz_notif_streak: "Você atingiu uma sequência de 7 dias!",
    quiz_notif_water: "Hora de beber água! Faltam 500ml."
  },
  EN: {
    // Welcome & Auth
    welcome_title: "Control your calories easily",
    welcome_subtitle: "The smartest way to reach your fitness goals with AI.",
    start_quiz: "Start Quiz",
    already_have_account: "Already have an account?",
    login_here: "Log in here",
    create_account: "Create account",
    welcome_back: "Welcome back",
    login_to_account: "Log in to your account",
    register_title: "Create your account",
    register_subtitle: "Save your progress and start your journey",
    auth_login_button: "Log In",
    auth_forgot_password: "Forgot password?",
    auth_no_account: "Don't have an account?",
    auth_password_placeholder: "Password",
    auth_have_account: "Already have an account?",
    auth_login_title: "Log In",
    auth_error_server: "Error connecting to server.",
    start_transformation: "Start My Transformation",
    continue: "Continue",
    back: "Back",
    skip: "Skip",

    // Quiz - Steps 1-10
    quiz_step_gender_title: "What is your gender?",
    quiz_gender_male: "Male",
    quiz_gender_female: "Female",
    quiz_gender_other: "Other",
    quiz_step_goal_title: "What is your main goal?",
    quiz_goal_lose: "Lose weight",
    quiz_goal_maintain: "Maintain weight",
    quiz_goal_gain: "Gain weight",
    quiz_step_age_title: "How old are you?",
    quiz_step_height_title: "What is your height?",
    quiz_step_weight_title: "What is your current weight?",
    quiz_step_target_weight_title: "What is your target weight?",
    quiz_day: "Day",
    quiz_month: "Month",
    quiz_year: "Year",
    quiz_step_feeling_title: "How do you feel today about your weight?",
    quiz_feeling_frustrated: "Frustrated and regretful for not acting sooner",
    quiz_feeling_avoidance: "I avoid looking in the mirror or taking photos",
    quiz_feeling_resigned: "Resigned, I've already gotten used to it",
    quiz_feeling_determined: "Determined to change finally",
    quiz_feeling_unhappy: "Unhappy",
    quiz_feeling_could_be_better: "Could be better",
    quiz_feeling_neutral: "Neutral",
    quiz_feeling_confident: "Confident",

    // Quiz - Velocity & Charts
    quiz_step_velocity_title: "How fast do you want to reach your goal?",
    quiz_velocity_per_week: "per week",
    quiz_velocity_subtitle: "per week",
    quiz_velocity_recommended: "Recommended pace",
    quiz_chart_loss_title: "Lose weight twice as fast with ProFit",
    quiz_chart_gain_title: "Gain mass twice as fast with ProFit",
    quiz_chart_subtitle: "Scientific studies show that using ProFit increases your success rate",
    quiz_chart_standard: "Standard approach",
    quiz_chart_profit: "With ProFit support",
    quiz_chart_footer: "ProFit makes it easy and keeps you committed",

    // Quiz - Obstacles & Goals
    quiz_step_obstacles_title: "What is holding you back from reaching your goals?",
    quiz_obstacles_subtitle: "Select all that apply",
    quiz_obstacle_consistency: "Lack of consistency",
    quiz_obstacle_habits: "Unhealthy eating habits",
    quiz_obstacle_support: "Lack of support",
    quiz_obstacle_schedule: "Busy schedule",
    quiz_obstacle_inspiration: "Lack of meal inspiration",
    quiz_step_conquer_title: "What would you like to achieve?",
    quiz_goals_subtitle: "Select all that apply",
    quiz_goal_health: "Eat and live healthier",
    quiz_goal_energy: "Increase my energy and mood",
    quiz_goal_motivation: "Stay motivated and consistent",
    quiz_goal_body: "Feel better about my body",

    // Quiz - Evolution Chart
    quiz_step_evolution_title: "Your muscles respond better than you think",
    quiz_evolution_3days: "3 Days",
    quiz_evolution_7days: "7 Days",
    quiz_evolution_30days: "30 Days",
    quiz_evolution_footer: "ProFit data shows that your protein synthesis increases from the first workout. After 7 days of consistency, muscle building entering a fast and constant pace!",

    // Quiz - Calories Education
    quiz_step_calories_intro: "Do you know what calories are and their importance for {goal}?",
    quiz_goal_text_lose: "losing weight",
    quiz_goal_text_gain: "gaining weight",
    quiz_goal_text_maintain: "maintaining your weight",
    quiz_yes: "Yes",
    quiz_no: "No",
    quiz_step_explain_title: "Let us explain!",
    quiz_explain_p1: "Calories are the energy that food provides to your body.",
    quiz_explain_p2: "Each food has a different amount:",
    quiz_explain_banana: "1 banana",
    quiz_explain_bread: "1 slice of bread",
    quiz_explain_rice: "1 spoon of rice",
    quiz_step_how_helps_title: "How does this help you {goal}?",
    quiz_helps_lose_p1: "To lose weight, you need to be in a calorie deficit, which is consuming fewer calories than your body spends.",
    quiz_helps_lose_p2: "If you spend 2000 calories per day, you need to eat about 1500-1700 to lose weight healthily.",
    quiz_helps_gain_p1: "To gain muscle mass, you need to be in a calorie surplus, which is consuming more calories than your body spends.",
    quiz_helps_gain_p2: "If you spend 2000 calories per day, you need to eat about 2300-2500 calories per day to gain weight.",
    quiz_helps_maintain_p1: "To maintain your weight, you need to consume the same amount of calories that your body spends daily.",
    quiz_helps_maintain_p2: "If you spend 2000 calories per day, you should consume around 2000 calories to maintain your weight.",
    quiz_helps_footer: "With ProFit, you will be able to implement this in a simple and safe way!",
    quiz_step_base_title: "Great, you already have a foundation!",
    quiz_base_p1: "We'll help you use this knowledge in your favor.",
    quiz_base_p2: "ProFit will now help you exactly reach your goal of {goal}.",

    // Quiz - Activity & Social Proof
    quiz_step_activity_title: "What is your physical activity level?",
    quiz_activity_subtitle: "This helps us calculate your daily calorie breakdown",
    quiz_activity_sedentary: "Sedentary",
    quiz_activity_sedentary_desc: "Office job, little exercise",
    quiz_activity_light: "Lightly Active",
    quiz_activity_light_desc: "Light exercise 1-3 days/week",
    quiz_activity_moderate: "Moderately Active",
    quiz_activity_moderate_desc: "Moderate exercise 3-5 days/week",
    quiz_activity_very: "Very Active",
    quiz_activity_very_desc: "Intense exercise 6-7 days/week",
    quiz_activity_extra: "Extremamente Ativo",
    quiz_activity_extra_desc: "Heavy training 2x a day, athlete",
    quiz_step_social_title: "Be like Lucas",
    quiz_social_subtitle: "And lose the desired weight with ProFit",
    quiz_social_before: "BEFORE",
    quiz_social_after: "AFTER",
    quiz_social_lost: "WEIGHT LOST",
    quiz_social_mass: "MUSCLE GAINED",
    quiz_social_duration: "DURATION",
    quiz_social_quote: "\"Losing weight seemed impossible, but ProFit changed everything.\"",
    quiz_social_user: "Lucas, ProFit user",

    // Emanuel - Gain Muscle
    quiz_emanuel_name: "Emanuel",
    quiz_emanuel_stats: "+12kg Lean Muscle",
    quiz_emanuel_duration: "6 Months",
    quiz_emanuel_quote: "\"ProFit gave me the exact path. I gained muscle I never thought possible just by changing my diet and training!\"",
    quiz_emanuel_user: "Emanuel, ProFit user",

    // Fatima - Lose Weight
    quiz_fatima_name: "Dona Fatima",
    quiz_fatima_stats: "-22kg Lost",
    quiz_fatima_duration: "4 Months",
    quiz_fatima_quote: "\"At 55, ProFit simplified my eating and today I feel 20 years younger!\"",
    quiz_fatima_user: "Dona Fatima, ProFit user",
    quiz_step_stories_title: "Success Stories",
    quiz_stories_subtitle: "Thousands of users reaching their goals",
    quiz_stories_count: "+1,000 users with ProFit",
    quiz_stories_card_title: "The only one I could maintain",
    quiz_stories_card_text: "I always gave up in 2 weeks. The gamification and real goals of ProFit kept me motivated. It's been 6 months of constant evolution!",
    quiz_stories_footer_title: "You're on the right track!",
    quiz_stories_footer_text: "Join thousands of satisfied users and start your journey today",

    // Quiz - Evolution (New Step 25)
    quiz_step_evolution_promo_title: "START YOUR EVOLUTION WITH PROFIT NOW",
    quiz_evolution_no_payment: "No payments made now",
    quiz_evolution_scan: "SCAN MEAL",
    quiz_evolution_gallery: "GALLERY",

    // Quiz - Why ProFit & Notifications
    quiz_step_why_title: "Why is ProFit the ideal app for you?",
    quiz_why_subtitle: "We combine science and artificial intelligence to facilitate your transformation",
    quiz_why_time_title: "Save your time",
    quiz_why_time_text: "Our AI calculates and records your food in seconds by photo, voice, or text. No more tedious manual searches.",
    quiz_why_freedom_title: "Food Freedom",
    quiz_why_freedom_text: "Learn to eat what you like while hitting your goals. Total control, zero useless restrictions.",
    quiz_why_conf_title: "Confidence in the Mirror",
    quiz_why_conf_text: "90% of users report feeling much more attractive and secure with their bodies in 30 days.",
    quiz_why_energy_title: "Daily Energy",
    quiz_why_energy_text: "Say goodbye to fatigue and bloating. Feel the difference in your energy levels in the first few days.",
    quiz_step_notif_title: "Stay Focused",
    quiz_notif_subtitle: "Activate notifications to receive personalized updates.",
    quiz_notif_stat: "Users with notifications are 3x more likely to reach goals.",
    quiz_notif_allow: "Allow Notifications",
    quiz_notif_later: "Maybe Later",
    quiz_notif_preview_report: "Your weekly progress report is ready!",
    quiz_notif_preview_meal: "Don't forget to record your lunch.",
    quiz_notif_preview_streak: "You hit a 7-day streak!",
    quiz_notif_preview_water: "Time to drink water! 500ml left.",

    // Quiz - Referral & Account
    quiz_step_referral_source_title: "Where did you hear about ProFit?",
    quiz_referral_source_subtitle: "This helps us improve our communication",
    quiz_referral_other: "Other",
    quiz_step_name_title: "Nice to meet you!",
    quiz_name_subtitle: "What is your name?",
    quiz_name_label: "Name",
    quiz_name_placeholder: "Enter your name",
    quiz_step_email_title: "Now let's create your account",
    quiz_email_subtitle: "Enter your best email",
    quiz_email_label: "Email",
    quiz_email_placeholder: "Enter your email",
    quiz_step_phone_title: "To finalize",
    quiz_phone_subtitle: "Share your phone with us",
    quiz_phone_label: "Phone",
    quiz_phone_placeholder: "Enter your phone",
    quiz_step_referral_code_title: "Do you have a referral code?",
    quiz_referral_code_subtitle: "You can skip this step",
    quiz_referral_code_label: "Referral Code",
    quiz_referral_code_placeholder: "Referral Code",

    // Quiz - Analysis & Result
    quiz_analysis_title_1: "Adjusting your experience",
    quiz_analysis_title_2: "Personalizing your ProFit strategy",
    quiz_analysis_title_3: "Creating your ProFit account",
    quiz_analysis_data: "Analyzing your data",
    quiz_analysis_health: "Calculating your health score",
    quiz_analysis_macros: "Calculating macros",
    quiz_analysis_review: "Reviewing everything",
    quiz_analysis_proof_title: "More than 5,000",
    quiz_analysis_proof_subtitle: "5-star reviews",
    quiz_step_final_title: "ProFit Plan Generated!",
    quiz_final_macros_desc: "Precision for your goal",
    quiz_final_button: "Access My Plan NOW",

    // Quiz Results - Step 34
    quiz_results_congrats: "Congratulations!",
    quiz_results_ready: "Your personalized plan is ready!",
    quiz_results_gain: "You should gain weight:",
    quiz_results_lose: "You should lose weight:",
    quiz_results_maintain_goal: "You should maintain your weight:",
    quiz_results_kg_until: "kg until",
    quiz_results_daily_rec: "Daily recommendation",
    quiz_results_edit_anytime: "You can edit this at any time",
    quiz_results_calories: "Calories",
    quiz_results_carbs: "Carbs",
    quiz_results_protein: "Protein",
    quiz_results_fats: "Fats",
    quiz_results_health_score: "Health Score",
    quiz_results_how_to_reach: "How to reach your goals",
    quiz_results_benefit_1: "See real results in days, not months",
    quiz_results_benefit_2: "Each meal brings you closer to your goal or pushes you away - choose right",
    quiz_results_benefit_3: "Accelerate your fat burning by eating the right calories",
    quiz_results_benefit_4: "The perfect balance between losing weight and maintaining energy",
    quiz_results_research_title: "Research we use to consider our calculations:",
    quiz_results_button: "Get your 3 free days",

    // Quiz Free Trial - Step 35
    quiz_free_trial_title: "We want you to test FitCal for FREE",
    quiz_free_trial_subtitle: "No payments made now",
    quiz_scan_meal: "Scan Meal",
    quiz_gallery: "Gallery",
    quiz_privacy: "Privacy",
    quiz_restore: "Restore Purchases",
    quiz_terms: "Terms",

    // Quiz Subscription - Step 36
    quiz_timeline_title: "free... 😔",
    quiz_timeline_today_title: "Today",
    quiz_timeline_today_sub: "Get full access to FitCal to log your meals with AI",
    quiz_timeline_reminder_title: "In 0 Days - Reminder",
    quiz_timeline_reminder_sub: "We'll send a reminder that your free trial is ending",
    quiz_timeline_charge_title: "In 0 Days",
    quiz_timeline_charge_sub: "Your subscription will start {date} if you haven't canceled",
    quiz_subscription_monthly: "MONTHLY",
    quiz_subscription_price_mzn: "299 MT / month",
    quiz_subscription_change_body: "Don't miss the opportunity to change your body!",
    quiz_subscription_cancel_anytime: "Cancel anytime!",
    quiz_subscription_commitment: "No commitment, cancel anytime.",

    // Quiz - Dynamic Results (Steps 9-11)
    quiz_feeling_result_determinado_title: "You said you're determined. That's the energy you need. {todayStr}",
    quiz_feeling_result_determinado_sub: "Use that determination now to make it really happen.",
    quiz_feeling_result_conformado_title: "You said you already got used to it. But deep down you want to change. {todayStr}",
    quiz_feeling_result_conformado_sub: "Take the chance to step out of that comfort zone.",
    quiz_feeling_result_frustrado_title: "You said you feel frustrated. {todayStr}",
    quiz_feeling_result_frustrado_sub: "Don't let that frustration follow you all year. Change the route now.",
    quiz_feeling_result_evito_title: "You said you end up avoiding situations... {todayStr}",
    quiz_feeling_result_evito_sub: "It doesn't have to be like this. Break that cycle now.",
    quiz_goal_realistic_title: "{goalText} {goalVal} is a REALISTIC goal. And believe it: it's not hard at all!",
    quiz_goal_realistic_sub: "The secret to not giving up is starting with a possible goal like yours.",
    quiz_motivation_lose_title: "Reaching your best form is an investment in your health.",
    quiz_motivation_lose_sub: "Regardless of your starting point, focusing on the quality of your diet ensures more longevity and energy.",
    quiz_motivation_gain_title: "Your best version is waiting to be built.",
    quiz_motivation_gain_sub: "Gaining muscle mass cleanly requires precision in macros. With ProFit, you ensure that every calorie counts.",
    quiz_motivation_maintain_title: "Your health and vitality are your greatest asset.",
    quiz_motivation_maintain_sub: "Maintaining weight sustainably is what ensures longevity and energy. ProFit simplifies your routine.",

    // Dashboard
    dash_hello_morning: "Good morning",
    dash_hello_afternoon: "Good afternoon",
    dash_hello_night: "Good evening",
    dash_today: "Today",
    dash_consumed_today: "Consumed today",
    dash_goal: "Goal",
    dash_of_goal: "of goal",
    dash_protein: "Protein",
    dash_carbs: "Carbs",
    dash_fat: "Fat",
    dash_no_workout: "You don't have a workout plan yet.",
    dash_create_workout: "Create my plan",
    dash_workout_today: "Today's Workout",
    dash_workout_exercises: "Exercises",
    dash_workout_focus: "Focus",
    dash_workout_rest: "Take the time to rest and recover your energy! ⚡",
    dash_workout_view_all: "View full plan",
    dash_delete_meal: "Delete?",
    dash_yes: "Yes",
    dash_no: "No",
    dash_error_title: "Ops! Something went wrong",
    dash_retry: "Try again",
    dash_analysis_message: "View Message",
    dash_body_analysis: "View Body Analysis",
    dash_ai_vision: "AI Vision Based Analysis",
    dash_load_error: "Could not load your data. Check your connection.",
    dash_days_short: ['Sun', 'Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat'],
    dash_valid_until: "Valid until",
    dash_plan_expires_in: "Plan Expires in",
    dash_day: "day",
    dash_days: "days",
    dash_renew_now: "Renew now to keep Pro",
    dash_meals_title: "Logged meals",
    dash_view_all: "View all",
    dash_no_meals: "No meals logged recently.",
    dash_calories: "Calories",

    // Scan
    scan_analyzing: "Analyzing...",
    scan_identified_dish: "Identified Dish",
    scan_error_save: "An error occurred while saving the meal. Try again.",
    scan_share_title: "My Plate on ProFit",
    scan_share_text: "Check out my meal on ProFit! 🥗\nDish: {name}\nCalories: {calories} kcal\n{obs}",
    scan_link_copied: "Link copied to clipboard!",
    scan_ai_suggestion: "AI Suggestion",
    scan_daily_goal: "Daily Goal",
    scan_kcal_remaining: "kcal remaining",
    scan_nutrition_obs: "Nutritional Observation",
    scan_no_obs: "No observations for this dish.",
    scan_ingredients_title: "Identified Ingredients",
    scan_no_ingredients: "No ingredients identified.",
    scan_redo: "Redo",
    save: "SAVE",
    ok: "OK",
    success: "Success!",
    error: "Error",
    close: "Close",

    // Workouts
    wk_ia_title: "AI Workouts",
    wk_confirm: "Confirm",
    wk_back: "Back",
    wk_continue: "Continue",
    wk_generate: "Generate Plan",
    wk_fill_all: "Fill all fields to continue *",
    wk_loading_1: "We are creating your personalized plan...",
    wk_loading_2: "Analyzing your profile and history...",
    wk_loading_3: "Building your ideal training strategy...",
    wk_loading_4: "Finalizing technical details...",
    wk_sync_ia: "Syncing AI Master Coach",
    wk_active_plan_title: "Active Plan",
    wk_active_plan_msg: "You already have an active plan. Finish the current one before generating another.",
    wk_understand: "I understand",
    wk_ia_coach_title: "AI Master Coach 🤖",
    wk_ia_demand_msg: "Our AI is under high technical demand right now. Can we load a ProFit Transition Plan so you don't stay idle today?",
    wk_use_fallback: "Use Transition Plan",
    wk_step_1_title: "Building Your Custom Plan",
    wk_goal: "Goal",
    wk_level: "Level",
    wk_days_week: "Days/Week",
    wk_location: "Training Location",
    wk_age: "Age",
    wk_weight: "Weight (kg)",
    wk_height: "Height (cm)",
    wk_duration: "Duration",
    wk_intensity: "Intensity",
    wk_trained_before: "Have you trained before?",
    wk_training_time: "Training time",
    wk_body_focus: "Body Focus",
    wk_injuries: "Injuries or Pains?",
    wk_health_conditions: "Diseases or Conditions?",
    wk_notes: "Anything else?",
    wk_notes_placeholder: "Describe something important about you",
    wk_ia_analysis_title: "AI Body Analysis",
    wk_ia_analysis_desc: "Send a photo of your full body (front) for a MASTER analysis of strengths and weaknesses.",
    wk_select_photo: "Select Photo",
    wk_optional_formats: "Optional • JPG, PNG Formats",
    wk_ia_privacy_note: "The AI will analyze your estimated fat percentage and muscle structure to hyper-personalize your workout. Safe and private image.",
    wk_attention: "Attention ⚠️",
    wk_warning_msg: "You are about to generate your workout plan for the month.",
    wk_validity_msg: "This plan will be valid for the next 30 days and cannot be changed until the next cycle.",
    wk_update_now: "Update Now",
    wk_confirm_generate: "Confirm and Generate",
    wk_creating_custom: "We are creating your",
    wk_custom_plan: "Personalized Plan",
    wk_preparing: "Preparing your pro workout...",
    wk_workout_of: "Workout of",
    wk_coach_tip: "Master Coach Tip",
    wk_total_progress: "Total Progress",
    wk_exercises: "exercises",
    wk_rest: "rest",
    wk_suggested_load: "Suggested load",
    wk_volume: "Volume",
    wk_sets_series: "sets",
    wk_completed_sets: "Completed sets",
    wk_mark_done: "MARK EXERCISE AS DONE",
    wk_workout_done: "Workout Done! 🔥",
    wk_excellent_work: "Excellent work today. The body responds to consistent effort!",
    wk_est_kcal: "Est. Kcal",
    wk_time: "Time",
    wk_see_tomorrow: "See you tomorrow! 💪",

    // Bottom Nav
    nav_home: "Home",
    nav_scanner: "Scanner",
    nav_workout: "Workout",
    nav_profile: "Profile",

    // Profile
    profile_title: "Profile",
    profile_name_placeholder: "Your name",
    profile_goal_default: "GENERAL GOAL",
    profile_weight: "Weight",
    profile_height: "Height",
    profile_age: "Age",
    profile_years: "years",
    profile_menu_notifications: "Notifications",
    profile_menu_notifications_desc: "App alerts and reminders",
    profile_menu_achievements: "Achievements",
    profile_menu_achievements_desc: "Your badges and trophies",
    profile_menu_ai_chat: "AI Questions",
    profile_menu_ai_chat_desc: "Specialized fitness assistant",
    profile_menu_preferences: "Preferences",
    profile_menu_preferences_desc: "Theme and language",
    profile_menu_account: "Account",
    profile_menu_account_desc: "Personal data, Kcal Goal",
    profile_logout: "Logout",
    profile_notif_enabled: "Enabled",
    profile_notif_disabled: "Disabled",
    profile_modal_notif_title: "Disable notifications?",
    profile_modal_notif_msg: "You will stop receiving important reminders about your goals and meals.",
    profile_modal_confirm: "Disable",
    profile_modal_cancel: "Cancel",

    // Quiz Extra Components
    quiz_lucas_lost_val: "-20Kg",
    quiz_lucas_duration_val: "3 Months",
    quiz_success_users: "+1,000 users with ProFit",
    quiz_success_comment_title: "The only one I could maintain",
    quiz_success_comment_text: "I always gave up in 2 weeks. The gamification and real goals of ProFit kept me motivated. It's been 6 months of constant evolution!",
    quiz_success_footer_title: "You're on the right track!",
    quiz_success_footer_text: "Join thousands of satisfied users and start your journey today",
    quiz_notif_now: "NOW",
    quiz_notif_report: "Your weekly progress report is ready!",
    quiz_notif_lunch: "Don't forget to record your lunch.",
    quiz_notif_streak: "You hit a 7-day streak!",
    quiz_notif_water: "Time to drink water! 500ml left."
  }
};

export const LanguageProvider = ({ children }: { children: ReactNode }) => {
  const [language, setLanguageState] = useState<Language>(() => {
    const saved = localStorage.getItem('appLanguage');
    return (saved === 'PT' || saved === 'EN') ? saved : 'PT';
  });

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem('appLanguage', lang);
  };

  const langData = translations[language];

  return (
    <LanguageContext.Provider value={{ language, setLanguage, langData }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
